apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-spring-deployment
  labels:
    app: app1-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-spring
  template:
    metadata:
      labels:
        app: app1-spring
    spec:
      containers:
        - name: app1-spring
          image: demaksac.azurecr.io/springboot:52
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1-spring-loadbalancer-service
  labels:
    app: app1-spring
spec:
  type: NodePort
  selector:
    app: app1-spring
  ports:
    - port: 80
      targetPort: 80
