apiVersion : apps/v1
kind: Deployment
metadata:
  name: krishnaspringbootapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krishnaspringbootapp
  template:
    metadata:
      labels:
        app: krishnaspringbootapp 
    spec:
      containers:
        - name: krishnaspringbootapp 
          image: demaksac.azurecr.io/springboot:52
          ports:
          - containerPort: 80
